four51.app.factory('MenuImageSelector', function() {
    var _gallery1 = {
        'All Natural Beef Burger Raised Without Antibiotics_3.75x5.45.jpg': ['All Natural Beef Burger Raised Without Antibiotics'],
        'All Natural Center Cut Pork Chop Riased Without Antibiotics_3.75x5.45.jpg': ['All Natural Center Cut Pork Chop Raised Without Antibiotics'],
        'All Natural Proscuitto Raised without Antibiotics_3.75x5.45.jpg': ['All Natural Prosciutto Raised Without Antibiotics'],
        'All Natural Soppressata Raised without Antibiotics_3.75x5.45.jpg': ['All Natural Uncured Soppressata Raised Without Antibiotics'],
        'All Natural Uncured Beef Hot Dog Raised without Antibiotics_3.75x5.45.jpg': ['All Natural Uncured All Beef Hot Dog Raised Without Antibiotics'],
        'Coho Salmon_3.75x5.45.jpg': ['Coho Salmon'],
        'Fresh Crumb Breaded Shrimp_3.75x5.45.jpg': ['Fresh Crumb Breaded Shrimp'],
        'Gluten-Free Breaded Chicken Chunk Raised Without Antibiotics_3.75x5.45.jpg': ['Gluten Free Breaded Chicken Chunk Raised Without Antibiotics'],
        'Hibiscus Berry Iced Tea made with Rainforest Alliance green tea_3.75x5.45.jpg': ['Hibiscus Berry Iced Tea made with Rainforest Alliance green tea'],
        'Mayonnaise made with Cage Free Eggs_3.75x5.45.jpg': ['Mayonnaise made with Cage Free Eggs'],
        'Moroccan Mint Iced Tea made with Rainforest Alliance Green Tea_3.75x5.45.jpg': ['Moroccan Mint Iced Tea made with Rainforest Alliance Green Tea'],
        'Non-GMO Canola Oil Based Cooking Spray_3.75x5.45.jpg': ['Non GMO Canola Oil based Cooking Spray'],
        'Non-GMO Demi Baguette Roll_3.75x5.45.jpg': ['Non GMO Demi Baguette Roll'],
        'Non-GMO Everything Wheat Sliced Sandwich Bread_3.75x5.45.jpg': ['Non- GMO Everything Wheat Sliced Sandwich Bread'],
        'Non-GMO Premium Brioche Style Hot Dog Bun_3.75x5.45.jpg': ['Non GMO Premium Brioche style Hot Dog Bun'],
        'Non-GMO Ripened Sliced Sweet Plantains_3.75x5.45.jpg': ['Non GMO Ripened Sliced Sweet Plantains'],
        'Non-GMO White Sliced Sandwich Bread_3.75x5.45.jpg': ['Non-GMO White Sliced Sandwich Bread'],
        'Organic California Blend Vegetables_3.75x5.45.jpg': ['Premium Organic California Blend Vegetables'],
        'Organic Fingerling Potato Blend_3.75x5.45.jpg': ['Organic Fingerling Potato Blend'],
        'Organic Four Berry Assortment_3.75x5.45.jpg': ['Organic Four Berry Assortment'],
        'Organic Harvest Blend_3.75x5.45.jpg': ['Organic Harvest Blend'],
        'Organic Snappy Slaw Blend_3.75x5.45.jpg': ['Organic Slaw Blend'],
        'Premium Banana Chocolate Swirl Cake made with Rainforest Alliance Bananas and Fair Trade Chocolate_3.75x5.45.jpg': ['Premium Banana Chocolate Swirl Cake made with Rainforest Alliance Bananas and Fair Trade Chocolate'],
        'Premium Cage Free Large Brown Eggs_3.75x5.45.jpg': ['Premium Cage Free Large Brown Shell Eggs'],
        'Pressed Pollock Fillets_3.75x5.45.jpg': ['Pressed Pollock Fillets'],
        'Ultra-Pasteurized Organic Milk_3.75x5.45.jpg': ['Organic 2% Milk'],
        'Yellowfin Tuna Loin_3.75x5.45.jpg': ['Yellowfin Tuna Loin'],
        'Boneless_Pork_Loin.jpg': ['Boneless Pork Loin'],
        'Cape_Shark_Tenders.jpg': ['Cape Shark Tenders'],
        'Cheesecake.jpg': ['Cheesecake'],
        'Chicken_Breast_Slices.jpg': ['Chicken Breast Slices'],
        'Chicken_Wings.jpg': ['Chicken Wings'],
        'Cornbread_Muffin.jpg': ['Cornbread Muffin'],
        'Grilled_Mixed_Vegetables.jpg': ['Grilled Mixed Vegetables'],
        'Liquid_Whole_Eggs.jpg': ['Liquid Whole Eggs'],
        'Pepper_Bacon_Sausage.jpg': ['Pepper Bacon Sausage'],
        'Premium_Belgian_Waffle.jpg': ['Premium Belgian Waffle'],
        'Rotini_Broccoli_Cheddar_Salad.jpg': ['Rotini Broccoli Cheddar Salad'],
        'Smoked_Norwegian_Salmon.jpg': ['Smoked Norwegian Salmon'],
        'Smoked_Norwegian_Trout.jpg': ['Smoked Norwegian Trout'],
        'Spicy_Battered_Cauliflower.jpg': ['Spicy Battered Cauliflower'],
        'Sweet_Potato_House_Fry.jpg': ['Sweet Potato House Fry'],
        'Uptown_Par-Fried_Chicken_Thigh.jpg': ['Uptown Par-Fried Chicken Thigh'],
        'Veggie_Crunch_Salad.jpg': ['Veggie Crunch Salad']
    };

    var _gallery2 = {
        'All Natural Beef Burger Raised without Antibiotics_3.75x2.812.jpg': ['All Natural Beef Burger Raised Without Antibiotics'],
        'All Natural Center Cut Pork Chop Raised without Antibiotics_3.75x2.812.jpg': ['All Natural Center Cut Pork Chop Raised Without Antibiotics'],
        'All Natural Proscuitto Raised without Antibiotics_3.75x2.812.jpg': ['All Natural Prosciutto Raised Without Antibiotics'],
        'All Natural Soppressata Raised without Antibiotics_3.75x2.812.jpg': ['All Natural Uncured Soppressata Raised Without Antibiotics'],
        'All Natural Uncured Beef Hot Dog Raised without Antibiotics_3.75x2.812.jpg': ['All Natural Uncured All Beef Hot Dog Raised Without Antibiotics'],
        'Coho Salmon_3.75x2.812.jpg': ['Coho Salmon'],
        'Fresh Crumb Breaded Shrimp_3.75x2.812.jpg': ['Fresh Crumb Breaded Shrimp'],
        'Gluten-Free Breaded Chicken Chunk Raised without Antibiotics_3.75x2.812.jpg': ['Gluten Free Breaded Chicken Chunk Raised Without Antibiotics'],
        'Hibiscus Berry Iced Tea made with Rianforest Alliance Green Tea_3.75x2.812.jpg': ['Hibiscus Berry Iced Tea made with Rainforest Alliance green tea'],
        'Mayonnaised Made with Cage Free Eggs_3.75x2.812.jpg': ['Mayonnaise made with Cage Free Eggs'],
        'Moroccan Mint Iced Tea made with Rainforest Alliance Green Tea_3.75x2.812.jpg': ['Moroccan Mint Iced Tea made with Rainforest Alliance Green Tea'],
        'Non-GMO Canola Oil Based Cooking Spray_3.75x2.812.jpg': ['Non GMO Canola Oil based Cooking Spray'],
        'Non-GMO Demi Baguette Roll_3.75x2.812.jpg': ['Non GMO Demi Baguette Roll'],
        'Non-GMO Evertyhing Wheat Sliced Sandwich Bread_3.75x2.812.jpg': ['Non- GMO Everything Wheat Sliced Sandwich Bread'],
        'Non-GMO Premium Brioche Style Hot Dog Bun_3.75x2.812.jpg': ['Non GMO Premium Brioche style Hot Dog Bun'],
        'Non-GMO Ripened Sliced Sweet Plantains_3.75x2.812.jpg': ['Non GMO Ripened Sliced Sweet Plantains'],
        'Non-GMO White SLiced Sandwich Bread_3.75x2.812.jpg': ['Non-GMO White Sliced Sandwich Bread'],
        'Organic California Blend Vegetables_3.75x2.812.jpg': ['Premium Organic California Blend Vegetables'],
        'Organic Fingerling Potato Blend_3.75x2.812.jpg': ['Organic Fingerling Potato Blend'],
        'Organic Four Berry Assortment_3.75x2.812.jpg': ['Organic Four Berry Assortment'],
        'Organic Harvest Blend_3.75x2.812.jpg': ['Organic Harvest Blend'],
        'Organic Snappy Slaw Blend_Mag_3.75x2.812.jpg': ['Organic Slaw Blend'],
        'Premium Banana Chocolate Swirl Cake made with Rainforest Alliance Bananas and Fair Trade Chocolate_3.75x2.812.jpg': ['Premium Banana Chocolate Swirl Cake made with Rainforest Alliance Bananas and Fair Trade Chocolate'],
        'Premium Cage Free Large Brown Eggs_3.75x2.812.jpg': ['Premium Cage Free Large Brown Shell Eggs'],
        'Pressed polock Fillets_3.75x2.812.jpg': ['Pressed Pollock Fillets'],
        'Ultra-Pasteurized Organic Milk_3.75x2.812.jpg': ['Organic 2% Milk'],
        'Yellowfin Tuna Loin_3.75x2.812.jpg': ['Yellowfin Tuna Loin'],
        'Boneless_Pork_LoinF2.jpg': ['Boneless Pork Loin'],
        'Cape_Shark_TendersF2.jpg': ['Cape Shark Tenders'],
        'CheesecakeF2.jpg': ['Cheesecake'],
        'Chicken_Breast_SlicesF2.jpg': ['Chicken Breast Slices'],
        'Chicken_WingsF2.jpg': ['Chicken Wings'],
        'Cornbread_MuffinF2.jpg': ['Cornbread Muffin'],
        'Grilled_Mixed_VegetablesF2.jpg': ['Grilled Mixed Vegetables'],
        'Liquid_Whole_EggsF2.jpg': ['Liquid Whole Eggs'],
        'Pepper_Bacon_SausageF2.jpg': ['Pepper Bacon Sausage'],
        'Premium_Belgian_WaffleF2.jpg': ['Premium Belgian Waffle'],
        'Rotini_Broccoli_Cheddar_SaladF2.jpg': ['Rotini Broccoli Cheddar Salad'],
        'Smoked_Norwegian_SalmonF2.jpg': ['Smoked Norwegian Salmon'],
        'Smoked_Norwegian_TroutF2.jpg': ['Smoked Norwegian Trout'],
        'Spicy_Battered_CauliflowerF2.jpg': ['Spicy Battered Cauliflower'],
        'Sweet_Potato_House_FryF2.jpg': ['Sweet Potato House Fry'],
        'Uptown_Par-Fried_Chicken_ThighF2.jpg': ['Uptown Par-Fried Chicken Thigh'],
        'Veggie_Crunch_SaladF2.jpg': ['Veggie Crunch Salad']
    };

    var _path1 = "http://www.four51.com/Themes/Custom/78ad1fd0-1ab1-4bd2-9a1a-a556f7bc77dc/ImageSelectorImages/MenuInsertF1/"
    var _path2 = "http://www.four51.com/Themes/Custom/78ad1fd0-1ab1-4bd2-9a1a-a556f7bc77dc/ImageSelectorImages/MenuInsertF2/"

    return {
        gallery1 : _gallery1,
        gallery2: _gallery2,
        path1 : _path1,
        path2: _path2
    }
});