four51.app.factory('TableTentImageSelector', function() {
    var _ScoopIssue2Spring2012 = {
        'CL_ShortRibChuckPatty_GLM1.jpg': ['CL Short Rib Chuck Patty'],
        'CL_ShortRibs.jpg': ['CL Short Ribs'],
        'PF_BreadChickenFritters_APP5.jpg': ['PF Breaded Chicken Fritters A'],
        'PF_BreadChickenFritters_SSC.jpg': ['PF Breaded Chicken Fritters B']
    };

    var _ScoopIssue3Summer2012 = {
        'CL_StuffedPasta_SCC.jpg': ['CL Stuffed Pasta'],
        'CL_StuffedPastaMushTruffCappellucci_LBL1.jpg': ['CL Stuffed Pasta Mushroom Truffle'],
        'CL_StuffedPastaPumpkin_LBL1.jpg': ['CL Stuffed Pasta Pumpkin'],
        'CL_StuffedPastaRoastTomatMozzGirasoli_LBL1.jpg': ['CL Stuffed Pasta Roast Tomato Mozz Girasoli'],
        'HB_CalamariFries.jpg': ['HB Calamari Fries'],
        'HB_CalamariFries_APP1.jpg': ['HB Calamari Fries Plated'],
        'HB_CalamariRings.jpg': ['HB Calamari Rings A'],
        'HB_CalamariRings_APP1.jpg': ['HB Calamari Rings B'],
        'HB_CalamariRings_SSC.jpg': ['HB Calamari Rings C']
    };

    var _ScoopIssue4Fall2012 = {
        'CL_FullyCookedPorkBelly_LBL1.jpg': ['CL Fully Cooked Pork Belly'],
        'MK_Empanada_1.jpg': ['MK Empanada 1'],
        'MK_Empanada_2.jpg': ['MK Empanada 2'],
        'MK_Empanada_3.jpg': ['MK Empanada 3'],
        'PF_FriedChicken_SSC.jpg': ['PF Fried Chicken']
    };

    var _ScoopIssue5Spring2013 = {
        'Chicken_Tenders_A.jpg': ['Chicken Tenders'],
        'CL_AppleCinnGourmetMuffin_GLM1.jpg': ['CL Apple Cinnamon Gourmet Muffins A'],
        'CL_AppleCinnGourmetMuffin_LBL.jpg': ['CL Apple Cinnamon Gourmet Muffins B'],
        'CL_AppleTart_LBL.jpg': ['CL Apple Tart'],
        'CL_BlueberryGourmetMuffins_GLM1.jpg': ['CL Blueberry Gourmet Muffin'],
        'CL_BlueberryMuffin_B.jpg': ['CL Blueberry Muffin'],
        'CL_ChocolateIceCream_LBL.jpg': ['CL Chocolate Ice Cream'],
        'CL_ChocolateIceCream_SSC.jpg': ['CL Vanilla Ice Cream'],
        'CL_DoubleChocGourmetMuffin_GLM1.jpg': ['CL Double Chocolate Gourmet Muffin'],
        'CL_DoubleChocGourmetMuffin_LBL.jpg': ['CL Double Chocolate Gourmet Muffin Plate'],
        'CL_HighGlossBuns_LBL-2.jpg': ['CL High Gloss Buns'],
        'CL_Ice_cream_Appletart_A.jpg': ['CL Ice Cream and Apple Tart'],
        'CL_Muffins_A.jpg': ['CL Muffins A'],
        'CL_Muffins_B.jpg': ['CL Muffins B'],
        'CL_RusticAppleTart_SSC.jpg': ['CL Rustic Apple Tart'],
        'CL_SandwichBunss_SSC.jpg': ['CL Sandwich Buns'],
        'CL_SeededSaletPepperSandwichBuns_LBL.jpg': ['CL Seeded Salt&Pepper Sandwich Buns'],
        'CL_ShrimpCrabCake_A.jpg': ['CL Shrimp Crabcake A'],
        'CL_SouthernStyleShrimpCrabCakes_LBL.jpg': ['CL Southern Style Shrimp Crab Cakes'],
        'CL_TraditionalSandwichBuns_LBL.jpg': ['CL Traditional Sandwich Buns'],
        'CL_VanillaBean_IceCrm_AppleTart.jpg': ['CL Vanilla Bean Ice Cream Apple Tart'],
        'Fries_A.jpg': ['Fries A'],
        'Fries_C.jpg': ['Fries B'],
        'GF_HorseradshChiveCheddarCheeseSlices_GLM1.jpg': ['GF Horseradish Chive Cheddar Cheese Slices'],
        'MD_ChickenBreast.jpg': ['MD Chicken Breast'],
        'MD_OvenRoastedChickenBreast_GLM1.jpg': ['MD Oven Roasted Chicken Breast'],
        'MK_CheeseBites_1.jpg': ['MK Cheese Bites'],
        'MK_MozzarellaEmpanada.jpg': ['MK Mozzarella Empanada'],
        'MK_SnackinBuns_BBQ.jpg': ['MK Snackin Buns BBQ'],
        'MK_SnackinBuns_PhillyCheese.jpg': ['MK Snackin Buns Philly Cheese'],
        'MK_SnackinBuns_SSC.jpg': ['MK Snackin Buns'],
        'MON_BostonMolassesBakedBeans_A.jpg': ['MON Boston Molasses Baked Beans A'],
        'MON_BostonMolassesBakedBeans_C.jpg': ['MON Boston Molasses Baked Beans B'],
        'MON_BourbonMolassesBakedBeans_SSC.jpg': ['MON Bourbon Molasses Baked Beans'],
        'MON_SweetPancakes_2.jpg': ['MON Sweet Pancakes'],
        'MON_SweetPankcakeMix_LBL.jpg': ['MON Sweet Pancake Mix'],
        'PF_BourbonBacon_A.jpg': ['PF Bourbon Bacon']
    };

    var _ScoopIssue6Summer2013 = {
        'Capresse_BG_A.jpg': ['Capresse'],
        'MD-Cover_V2_D_r2.jpg': ['MD Cover'],
        'MD-Cuban_Sandwich_BG_A.jpg': ['MD Cuban Sandwich'],
        'MD_GourmetHam.jpg': ['MD Gourmet Ham'],
        'MD-hot_dogs.jpg': ['MD Hot Dogs'],
        'MD-Roast_Beef_Baguette_BG.jpg': ['MD Roast Beef Baguette']
    };

    var _ScoopIssue7Fall2013 = {
        'CL-BerryTart_C_Scoop.jpg': ['CL BerryTart One'],
        'CL-BerryTart_Web.jpg': ['CL BerryTart Two'],
        'CL-HummusFalafal_A_Scoop.jpg': ['CL Hummus Falafal'],
        'CL-RibeyeRoast_Scoop.jpg': ['CL Ribeye Roast'],
        'CL-Staybowlizer_B.jpg': ['CL Staybowlizer'],
        'CVF-BrusselSprout_B_Scoop.jpg': ['CVF Brussel Sprout'],
        'CVF-Sprouts_A_Scoop.jpg': ['CVF Sprouts'],
        'DP-CotijaCheese_Scoop.jpg': ['DP Cotija Cheese'],
        'DP-FonditoCheese_Scoop.jpg': ['DP Fondito Cheese'],
        'MD-HoneyHam_F_Scoop.jpg': ['MD Honey Ham'],
        'MK-ChipotleBursts_D_Scoop.jpg': ['MK Chipotle Bursts'],
        'MON-Falafel_Web.jpg': ['MON Falafel'],
        'MON-FalafelHummus_A_Scoop.jpg': ['MON Falafel lHummus'],
        'MON-SweetPotatoFries_C_Scoop.jpg': ['MON Sweet Potato Fries'],
        'PF-ChickenFilet_B_Scoop.jpg': ['PF Chicken Filet'],
        'PF-ChickenTender_A_Scoop.jpg': ['PF Chicken Tender'],
        'RS_KeyLimeJuice_2.jpg': ['RS Key Lime Juice'],
        'BoldBeautifulSprouts.jpg': ['BoldBeautifulSprouts'],
        'GetWrappedUp.jpg': ['GetWrappedUp'],
        'HamItUp.jpg': ['HamItUp'],
        'PersonalPizza.jpg': ['PersonalPizza'],
        'ThreeCheersForBeer.jpg': ['ThreeCheersForBeer'],
        'WhatASweetTart.jpg': ['WhatASweetTart'],
        'YouWillFallForFalafel.jpg': ['YouWillFallForFalafel']
    };

    var _ScoopIssue8Spring2014 = {
        'CL SaltedCarmelIceCream1.jpg': ['CL Salted Carmel Ice Cream 1'],
        'CL SaltedCarmelIceCream2.jpg': ['CL Salted Carmel Ice Cream 2'],
        'CL TurkeyBurger1.jpg': ['CL Turkey Burger 1'],
        'CL TurkeyBurger2.jpg': ['CL Turkey Burger 2'],
        'CL TurkeyBurger3.jpg': ['CL Turkey Burger 3'],
        'CVF KaleSaladMix.jpg': ['CVF Kale Salad Mix'],
        'CVF NapaCabbageBlend1.jpg': ['CVF Napa Cabbage Blend 1'],
        'CVF NapaCabbageBlend2.jpg': ['CVF Napa Cabbage Blend 2'],
        'D BlackCherryCheesecake.jpg': ['D Black Cherry Cheesecake'],
        'D Cheesecakes.jpg': ['D Cheesecakes'],
        'D RicottaCheesecake2.jpg': ['D Ricotta Cheesecake 2'],
        'D RicottaCheesecakes.jpg': ['D Ricotta Cheesecakes'],
        'DP StreetTacos.jpg': ['DP Street Tacos'],
        'GF GhostPepperCheese.jpg': ['GF Ghost Pepper Cheese'],
        'HB FreshCrumbCod.jpg': ['HB Fresh Crumb Cod'],
        'HB IslandStyleMahiMahi.jpg': ['HB Island Style Mahi Mahi'],
        'M SweetPotatoWaffleFries.jpg': ['M Sweet Potato Waffle Fries'],
        'M WaffleFries.jpg': ['M Waffle Fries'],
        'MK BeerPretzelCheeseBite1.jpg': ['MK Beer Pretzel Cheese Bite 1'],
        'MK BeerPretzelCheeseBite2.jpg': ['MK Beer Pretzel Cheese Bite 2'],
        'MK BeerPretzelCheeseBite3.jpg': ['MK Beer Pretzel Cheese Bite 3'],
        'MK BeerPretzelCheeseBite4.jpg': ['MK Beer Pretzel Cheese Bite 4'],
        'PF BuffaloChickenChunks.jpg': ['PF Buffalo Chicken Chunks'],
        'PF BuffaloChickenFilet1.jpg': ['PF Buffalo Chicken Filet 1'],
        'PF BuffaloChickenFilet2.jpg': ['PF Buffalo Chicken Filet 2'],
        'PF BuffaloChickenTenders.jpg': ['PF Buffalo Chicken Tenders'],
        'RS Lemonades.jpg': ['RS Lemonades']
    };

    var _ScoopIssue9Summer2014 = {
        'BeefBrisket 5.3x3.58.jpg': ['Beef Brisket'],
        'BeefRibBites 5.3x3.58.jpg': ['Beef Rib Bites'],
        'BlackBeanVeggieBurger 5.3x3.58.jpg': ['Black Bean Veggie Burger'],
        'BuffaloRicottaSpinachRapiniTondi 5.3x3.58.jpg': ['Buffalo Ricotta Spinach Rapini Tondi'],
        'CakePops 5.3x3.58.jpg': ['Cake Pops'],
        'Cakies 5.3x3.58.jpg': ['Cakies'],
        'ChickenChunks 5.3x3.58.jpg': ['Chicken Chunks'],
        'ChickenFilet 5.3x3.58.jpg': ['Chicken Filet'],
        'ChickenTenders 5.3x3.58.jpg': ['Chicken Tenders 2'],
        'CodFries 5.3x3.58.jpg': ['Cod Fries'],
        'CookiesMilk_Cakies 5.3x3.58.jpg': ['Cookies Milk Cakies'],
        'CranberryLemonMuffin 5.3x3.58.jpg': ['Cranberry Lemon Muffin'],
        'EggWhiteMix 5.3x3.58.jpg': ['Egg White Mix'],
        'FishBites 5.3x3.58.jpg': ['Fish Bites'],
        'FreshTomatoSalsa 5.3x3.58.jpg': ['Fresh Tomato Salsa'],
        'GhostPepperMangoSalsa 5.3x3.58.jpg': ['Ghost Pepper Mango Salsa'],
        'GingerTeaMuffin 5.3x3.58.jpg': ['Ginger Tea Muffin'],
        'HeirloomtomatoBurrataMezzalune 5.3x3.58.jpg': ['Heirloom Tomato Burrata Mezzalune'],
        'ItalianSausages 5.3x3.58.jpg': ['Italian Sausages'],
        'KaleTrio 5.3x3.58.jpg': ['Kale Trio'],
        '2KaleTrio 5.3x3.58.jpg': ['Kale Trio 2'],
        'MON_SweetPankcakeMix 5.3x3.58.jpg': ['MON Sweet Pankcake Mix'],
        'NTP Black Bean Burger 5.3x3.58.jpg': ['NTP Black Bean Burger'],
        'PuzzlePotatoes 5.3x3.58.jpg': ['Puzzle Potatoes'],
        'Raspberry_Cakies 5.3x3.58.jpg': ['Raspberry Cakies'],
        'Savory Egg Mix 5.3x3.58.jpg': ['Savory Egg Mix']
    };

    var _ScoopIssue10Fall2014 = {
        'CL_Brat_web.jpg': ['CL_Bratwurst'],
        'CL_ChedJalapMeatBall_web.jpg': ['CL Cheddar Jalapeno Meatball'],
        'CL_CraftMexicanStyleCola.jpg': ['CL Craft Mexican Style Cola'],
        'CL_CraftRootBeer.jpg': ['CL Craft Root Beer'],
        'CL_CraftSodas_All3.jpg': ['CL Craft Sodas All 3'],
        'CL_CraftSpicyGingerBeer.jpg': ['CL Craft Spicy Ginger Beer'],
        'CL_ItalMeatBall_web.jpg': ['CL Italian Meatball'],
        'CL_Short_Rib.jpg': ['CL Short Rib'],
        'CVF_HeirloomTomatoes.jpg': ['CVF Heirloom Tomatoes'],
        'CVF_SunsetBlend.jpg': ['CVF Sunset Blend'],
        'DEV_LemonRaspberry.jpg': ['DEV Lemon Raspberry'],
        'DEV_SweetPotatoMapleLayeredCheeseCake.jpg': ['DEV Sweet Potato Maple Layered Cheesecake'],
        'HarborBanks_Calamari_Web.jpg': ['Harbor Banks Calamari'],
        'HB_TossShrmp_Web.jpg': ['HB Tossed Shrmp'],
        'HV_Pepperoni.jpg': ['HV Pepperoni'],
        'MD_Ham_Web.jpg': ['MD Ham'],
        'MD_HnyRstTurkey_Web.jpg': ['MD Honey Roast Turkey'],
        'MD_KettleCookedPotatoChips_All3.jpg': ['MD Kettle Cooked Potato Chips All 3'],
        'MD_KettleCookedPotatoChips_Barbecue.jpg': ['MD Kettle Cooked Potato Chips Barbecue'],
        'MD_KettleCookedPotatoChips_JalapenoCheddar.jpg': ['MD Kettle Cooked Potato Chips Jalapeno Cheddar'],
        'MD_KettleCookedPotatoChips_Original.jpg': ['MD Kettle Cooked Potato Chips Original'],
        'MK_BaconWrappedChicken_Web.jpg': ['MK Bacon Wrapped Chicken'],
        'MK_CowboyChili_Web.jpg': ['MK Cowboy Chili'],
        'MK_GreenChiliSoup_Web.jpg': ['MK Green Chili Soup'],
        'MK_HamCroquette_Web.jpg': ['MK Ham Croquette'],
        'MON_PickleFries_v2.jpg': ['MON Pickle Fries v2'],
        'MON_PumpSpcMix_Scoop_B.jpg': ['MON Pumpkin Spice Mix Scoop B'],
        'MON_White&SweetPotatoFrites.jpg': ['MON White & Sweet Potato Frites'],
        'PJ_SesamePorkMiniPotStickers.jpg': ['PJ Sesame Pork Mini Pot Stickers'],
        'RS_SunflowerOil.jpg': ['RS Sunflower Oil']
    };

    var _ScoopIssue11Spring2015 = {
        'Scoop11_CL_BellyBurger.jpg': ['CL Belly Burger'],
        'Scoop11_CL_CarolinaBBQ.jpg': ['CL Carolina BBQ'],
        'Scoop11_CL_ChocColaMuffinMinis.jpg': ['CL Choc Cola Muffin Minis'],
        'Scoop11_CL_CoffeeIceCream.jpg': ['CL Coffee Ice Cream'],
        'Scoop11_CL_KansasCityBBQ.jpg': ['CL Kansas City BBQ'],
        'Scoop11_CL_NaturalFry.jpg': ['CL Natural Fry'],
        'Scoop11_CL_PorkCountryRibs.jpg': ['CL Pork Country Ribs'],
        'Scoop11_CL_StrawRhubMuffinMinis.jpg': ['CL Straw Rhub Muffin Minis'],
        'Scoop11_CL_TexasBBQ.jpg': ['CL Texas BBQ'],
        'Scoop11_CL_UmamiTurkeyPatty.jpg': ['CL Umami Turkey Patty'],
        'Scoop11_CVF_SuperfoodSlaw.jpg': ['CVF Superfood Slaw'],
        'Scoop11_GF_SmokyGhostCheeseBlend.jpg': ['GF Smoky Ghost Cheese Blend'],
        'Scoop11_HB_AlaskanCod.jpg': ['HB Alaskan Cod'],
        'Scoop11_HH_SweetCornHoagie.jpg': ['HH Sweet Corn Hoagie'],
        'Scoop11_HH_WheatBeerHoagie.jpg': ['HH Wheat Beer Hoagie'],
        'Scoop11_HV_SavoryBurger.jpg': ['HV Savory Burger'],
        'Scoop11_MD_ChickenSalad.jpg': ['MD Chicken Salad'],
        'Scoop11_MD_FireSmokedHam.jpg': ['MD Fire Smoked Ham'],
        'Scoop11_MD_LoadedBakedPotatoSalad.jpg': ['MD Loaded Baked Potato Salad'],
        'Scoop11_MK_GritStix.jpg': ['MK Grit Stix'],
        'Scoop11_MON_BaconAioli.jpg': ['MON Bacon Aioli'],
        'Scoop11_PF_PepperEncrustedBacon.jpg': ['PF Pepper Encrusted Bacon'],
        'Scoop11_PF_PulledPork.jpg': ['PF Pulled Pork']
    };

    var _ScoopIssue12Summer2015 = {
        'Scoop12_CL_MediterraneanStyleSliders.jpg': ['CL Greek Sliders'],
        'Scoop12_CS_RawBeefCuts_Enchiladas.jpg': ['CL Raw Beef Cuts Enchiladas'],
        'Scoop12_CVF_RoosterPotatoes.jpg': ['CVF Rooster Potatoes'],
        'Scoop12_DS_CroissantDonuts.jpg': ['DBS Croissant Donuts'],
        'Scoop12_HB_FlourDustedAlaskanSole.jpg': ['HB Flour Dusted Alaskan Sole'],
        'Scoop12_HB_SpicyTossNServeShrimp.jpg': ['HB Spicy Toss N Serve Shrimp'],
        'Scoop12_HH_PotatoHamburgerBuns.jpg': ['HH Potato Hamburger Buns'],
        'Scoop12_HH_PullApartCinnamonRoll.jpg': ['HH Pull Apart Cinnamon Roll'],
        'Scoop12_MON_CarolinaReaperWingSauce.jpg': ['MON Carolina Reaper Wing Sauce'],
        'Scoop12_MON_SmashedPotatoSkin.jpg': ['MON Smashed Potato Skins'],
        'Scoop12_PF_BeerBatterChixChunks.jpg': ['PF Beer Battered Chix Chunks'],
        'Scoop12_PF_HardwoodChickenWings.jpg': ['PF Hardwood Chicken Wings'],
        'Scoop12_RS_WhiteStoneGroundGrits.jpg': ['RS White Stone Ground Grits'],
        'benedoughnut.jpg': ['Bene Doughnut'],
        'Caprese.jpg': ['Caprese'],
        'Cover.jpg': ['Cover'],
        'FilledGlazed.jpg': ['Filled Glazed'],
        'JuicyLuicy.jpg': ['Juicy Luicy'],
        'LobsterRoll.jpg': ['Lobster Roll'],
        'MonteCristo.jpg': ['Monte Cristo'],
        'MplBourbonBacon.jpg': ['Maple Bourbon Bacon'],
        'SaltySweet.jpg': ['Salty Sweet'],
        'SmkdSalmon.jpg': ['Smoked Salmon'],
        'Smore.jpg': ['Smores'],
        'StrawShortcake.jpg': ['Strawberry Shortcake']
    };

    var _ScoopIssue13Fall2015 = {
        'Bratwurst-5.3x3.5813.jpg': ['CL Bratwurst'],
        'Cinn-Brown-Sugar-Ice-Cream-5.3x3.5824.jpg': ['CL Cinnamon & Brown Sugar Ice Cream'],
        'Grass-Fed-Burger-5.3x3.5822.jpg': ['CL Grass Fed Burger'],
        'Grill Sidebar5.3x3.583.jpg': ['CL Grill Sidebar'],
        'Ground Chorizo-5.3x3.5820.jpg': ['CL Ground Chorizo'],
        'Hot-Italian-Sausage-5.3x3.5811.jpg': ['CL Hot Italian Sausage'],
        'Korean-Barbecue-Sauce5.3x3.587.jpg': ['CL Korean Barbecue Sauce'],
        'Sweet-Italian-Sausage-5.3x3.5812.jpg': ['CL Sweet Italian Sausage'],
        'Diced-Mangoes-5.3x3.584.jpg': ['CVF Fresh Diced Magnoes'],
        'Chipotle-Salsa-Picada-5.3x3.5817.jpg': ['DP Cipotle Salsa Picada'],
        'Cuban-Pork-Roast-5.3x3.5810.jpg': ['MD Cuban Seasoned Pork Roast'],
        'Salt-Vinegar-Chips-5.3x3.588.jpg': ['MD Salt Vinegar Chips'],
        'Sour-CreamChives-Chips-5.3x3.589.jpg': ['MD Sour Cream Chives Chips'],
        'Whiskey-Onion-Rings-5.3x3.5814.jpg': ['MK Whiskey Battered Onion Rings'],
        'Shot-Onion-Rings-5.3x3.5815.jpg': ['MKShot & Beer Battered Onion Rings'],
        'Mirepoix-Blend-5.3x3.5819.jpg': ['MON Mirepoix Blend'],
        'Puzzle-Potatoes-5.3x3.585.jpg': ['MON Puzzle Potatoes'],
        'Sweet-Potato-Waffle-Fries-5.3x3.586.jpg': ['MON Sweet Potato Waffle Fries'],
        'Nashville-Hot-Chicken-Wings-5.3x3.5816.jpg': ['PF Nashville Hot Chicken Wings'],
        'Iced-Latte--5.3x3.58.jpg': ['RIT Iced Latte'],
        'Grilled-Vegetables-5.3x3.5818.jpg': ['RS Grilled Vegetables'],
        'Thermometer-5.3x3.582.jpg': ['SUP Thermometer'],
        'Short-Rib-Slices-5.3x3.5821.jpg': ['SY Short Rib Slices']
    };

    var _ScoopIssue14Spring2016 = {
        'Valencia-Orange-Juice_5.25x3.377.jpg': ['RS 100% Valencia Orange Juice'],
        'All-Natural-Cherrywood-Smokde-Bacon_5.25x3.377.jpg': ['PF All Natural Cherrywood Smoked Bacon'],
        'All-Natural-Chipotle-Chicken-Thighs_5.25x3.377.jpg': ['CL All Natural Chipotle Chicken Thighs'],
        'All-Natural-Dark-turkey-Deli-Meat_5.25x3.377.jpg': ['MD All Natural Dark Turkey Deli Meat'],
        'All-Natural-Grass-Fed-Burger_5.25x3.377.jpg': ['SY All Natural Grass Fed Burger'],
        'All-Natural-Hickory-Smoked-Half-Chicken_5.25x3.377.jpg': ['CL All Natural Hickory Smoked half Chicken'],
        'All-Natural-Pork-Burnt-Ends_5.25x3.377.jpg': ['CL All Natural Pork Burnt Ends'],
        'All-Natural-Pork-Carnitas_5.25x3.377.jpg': ['CL All Natural Pork Carnitas'],
        'Avero-Gold_5.25x3.377.jpg': ['Avero Gold'],
        'Baby-Savoy-Spinach_5.25x3.377.jpg': ['CVF Baby Savoy Spinach Blend'],
        'Bavarian-Soft-Pretzel_5.25x3.377.jpg': ['CL Bavarian Soft Pretzel'],
        'Beer-Cheese-Dip_5.25x3.377.jpg': ['MK Beer Cheese Dip'],
        'Bianco-Buns_5.25x3.377.jpg': ['CL Bianco Buns'],
        'Blood-Orange-Sorbet_5.25x3.377.jpg': ['CL Blood Orange Sorbet'],
        'Bloody-Mary-Mix_5.25x3.377.jpg': ['RS Bloody Mary Mix'],
        'Cold-Brew-Coffee_Concentrate_5.25x3.377.jpg': ['RIT Cold Brew Coffee Concentrate'],
        'Fingerling-Sweet-Potatoes_5.25x3.377.jpg': ['CVF Fingerling Sweet Potatoes'],
        'Peper-and-Smoked-Sugar-Marinated-Alaska-Sockeye-Salmon_5.25x3.377.jpg': ['CL Pepper & Smoked Sugar Marinated Alaskan Sockey Salmon'],
        'Plain-Greek-Nonfat-Yogurt_5.25x3.377.jpg': ['GF Plain Greek Nonfat Yogurt'],
        'Riced-Cauliflower_5.25x3.377.jpg': ['CVF Riced Cauliflower'],
        'Roasted-Garlic-Buns_5.25x3.377.jpg': ['CL Roasted Garlic Buns'],
        'Slow-Roasted-Tomatoes_5.25x3.377.jpg': ['RS Slow Roasted Tomatoes'],
        'Spreadable-Brie_5.25x3.377.jpg': ['GF Spreadable Brie'],
        'Strawberry-Rhubarb-Greek-Nonfat-Yogurt_5.25x3.377.jpg': ['GF Strawberry Rhubarb Greek Nonfat Yogurt'],
        'Vanilla-Greek-Nonfat-Yogurt_5.25x3.377.jpg': ['GF Vanilla Greek Nonfat Yogurt'],
        'Watermelon-Limeade_5.25x3.377.jpg': ['RS Watermelon Limeade'],
        'White-and-Sweet-Potatoes-Frites_5.25x3.377.jpg': ['MON White & Sweet Potatoe Frites']
    };

    var _ScoopIssue16Fall2016 = {
        'CL_2561366_Demi Glace.jpg': ['CL Demi Glace'],
        'CL_3688845_Pumpkin Sweet Potato Tart.jpg': ['CL Pumpkin Sweet Potato Tart'],
        'CL_5816564_Pork Loin.jpg': ['CL Pork Loin'],
        'CL_7095673_Natural Chip.jpg': ['CL Natural Chip'],
        'CL_7265587_Compound Butter.jpg': ['CL Compound Butter'],
        'CL_8808558_Pumpkin Spice Ice Cream.jpg': ['CL Pumpkin Spice Ice Cream'],
        'CL_9192185_Yellowfin Tuna Slices.jpg': ['CL Yellowfin Tuna Slices'],
        'CL_9465510_Beef Chuck Short Ribs.jpg': ['CL Beef Chuck Short Ribs'],
        'CL_9636044_Natural Fry.jpg': ['CL Natural Fry'],
        'CVF_5225864_Beefsteak Tomatoes.jpg': ['CVF Beefsteak Tomatoes'],
        'CVF_8858409_Sunset Blend.jpg': ['CVF Sunset Blend'],
        'DEV_3998334_Smore Lava Cake.jpg': ['DEV Smore Lava Cake'],
        'GF_1056622_Blue Cheese Crumbles.jpg': ['GF Blue Cheese Crumbles'],
        'HB_1714015_Stuffed Shrimp and Grits.jpg': ['HB Stuffed Shrimp and Grits'],
        'HB_3305058_Stuff Shrimp Southwest.jpg': ['HB Stuffed Shrimp Southwest'],
        'HH_4496241_Hawaiian Slider Bun.jpg': ['HH Hawaiian Slider Bun'],
        'HH_4649764_Brown Breadstick.jpg': ['HH Brown Breadstick'],
        'HH_5825665_Garlic Ciabatta Breadstick.jpg': ['HH Garlic Ciabatta Breadstick'],
        'MD_2565976_Applewood Turkey Breast.jpg': ['MD Applewood Turkey Breast'],
        'MON_8869687_Pickle Fries.jpg': ['MON Pickle Fries'],
        'PF_7637713_Tenderloin Fritters.jpg': ['PF Tenderloin Fritters'],
        'RS_3616429_Grilled Artichokes.jpg': ['RS Grilled Artichokes'],
        'RS_9726983_Caramelized Onions.jpg': ['RS Caramelized Onions'],
        'SY_1846585_Bone Marrow.jpg': ['SY Bone Barrow'],
        'SY_7127324_Grass Fed Sliders.jpg': ['SY Grass Fed Sliders'],
        'SY_9518653_Ribeye.jpg': ['SY Ribeye']
    };

    var _ScoopIssue19Fall2017 = {
        'CL_4562638_CornMuffin.jpg': ['CL 4562638 Corn Muffin'],
        'CL_7617327_PorkLoin.jpg': ['CL 7617327 Pork Loin'],
        'CL_8808558_PumpSpiceIceCream.jpg': ['CL 8808558 Pumpkin Spice Ice Cream'],
        'CVF_4882244_1245731_VeggieCrunch.jpg': ['CVF 4882244 1247531 Veggie Crunch'],
        'CVF_9484217_RotiniSalad.jpg': ['CVF 9484217 Rotini Salad'],
        'DEV_6968216_BelgianWaffle.jpg': ['DEV 6968216 Belgian Waffle'],
        'DEV_8848186_Cheesecake.jpg': ['DEV 8848186 Cheesecake'],
        'GVF_5337015_LiquidEggs.jpg': ['GVF 5337015 Liquid Eggs'],
        'HB_3198825_CapeShark.jpg': ['HB 3198825 Cape Shark'],
        'HB_3216914_NorwegianTrout.jpg': ['HB 3216914 Norwegian Trout'],
        'HB_9823791_Norwegian-Salmon.jpg': ['HB 9823791 Norwegian Salmon'],
        'MK_6442845_Cauliflower.jpg': ['MK 6442845 Cauliflower'],
        'MON_7693799_SweetPotatoFry.jpg': ['MON 7693799 Sweet Potato Fry'],
        'PF_5815653_BaconSausage.jpg': ['PF 5815653 Bacon Sausage'],
        'PF_7699403_Chicken-Breast.jpg': ['PF 7699403 Chicken Breast'],
        'PF_8638719_Fried-Chicken-Thigh.jpg': ['PF 8638719 Fried Chicken Thigh'],
        'PF_9986258_ChickenWings.jpg': ['PF 9986258 Chicken Wings'],
        'RS_6537988_GrilledVeggies.jpg': ['RS 6537988 Grilled Veggies']
    };

    var _ScoopIssue18Summer2017 = {
        'CL_1088051_BeefBacon.jpg': ['CL 1088051 Beef Bacon'],
        'CL_1462630_ChickenTenderloin.jpg': ['CL 1462630 Chicken Tenderloin'],
        'CL_4493997_KouignAmann.jpg': ['CL 4493997 Kouign Amann'],
        'CL_9841549_StrawIceCream.jpg': ['CL 9841549 Strawberry Ice Cream'],
        'CVF_6866621_Kohlrabi.jpg': ['CVF 6866621 Kohlrabi'],
        'DEV_7025143_FunnelSticks.jpg': ['DEV 7025143 Funnel Sticks'],
        'DP_5584556_BorrachoBeans.jpg': ['DP 5584556 Borracho Beans'],
        'HB_7497505_StripedBass.jpg': ['HB 7497505 Striped Bass'],
        'HB_8417215_ArcticChar.jpg': ['HB 8417215 Artic Char'],
        'MD_3131044_BlkForestHam.jpg': ['MD 3131044 Black Forest Ham'],
        'MD_3413690_PopcornCheddar.jpg': ['MD 3413690 Popcorn Cheddar'],
        'MD_5620686_Popcorn_CocoOilSalt.jpg': ['MD 5620686 Popcorn Coconut Oil Salt'],
        'MK_3043713_MeatlessWings.jpg': ['MK 3043713 Meatless Wings'],
        'MK_4503294_BeerandCheeseDip.jpg': ['MK 4503294 Beer and Cheese Dip'],
        'MK_5922686_MeatlessCrumbles.jpg': ['MK 5922686 Meatless Crumbles'],
        'MK_5942572_CornNugget.jpg': ['MK 5942572 Corn Nugget'],
        'PF_3440787_JowlBacon.jpg': ['PF 3440787 Jowl Bacon'],
        'PF_8371487_Chick-arrones.jpg': ['PF 8371487 Chick-Arrones'],
        'SY_1345296_RWAChuck.jpg': ['SY 1345296 RWA Chuck']
    };

    var _ScoopIssue17Spring2017 = {
        'CL_1123735_Brisket.jpg': ['CL 1123735 Brisket'],
        'CL_1185055_Beef&Truffle Patties.jpg': ['CL 1185055 Beef & Truffle Patties'],
        'CL_2364959_Turkey Burger.jpg': ['CL 2364959 Turkey Burger'],
        'CL_2441422_Torta Buns.jpg': ['CL 2441422 Torta Buns'],
        'CL_2663960_Grilled Chicken Breast.jpg': ['CL 2663960 Grilled Chicken Breast'],
        'CL_3552695_Chicken Shawarma.jpg': ['CL 3552695 Chicken Shawarma'],
        'CL_4264835_Cheddar&Onion Bialys.jpg': ['CL 4264835 Cheddar & Onion Bialys'],
        'CL_8601429_Mini Naan.jpg': ['CL 8601429 Mini Naan'],
        'CL_9192185_Yellowfin Tuna Slices.jpg': ['CL 9192185 Yellowfin Tuna Slices'],
        'CVF_3116609_Lemony Rocket Blend.jpg': ['CVF 3116609 Lemony Rocket Blend'],
        'DEV_1195093_Black Velvet Cookie.jpg': ['DEV 1195093 Black Velvet Cookie'],
        'DEV_8848129_Lem-Ras Cheesecake.jpg': ['DEV 8848129 Lem-Ras Cheesecake'],
        'HB_9936302_Corkskrew Shrimp.jpg': ['HB 9936302 Corkskrew Shrimp'],
        'MD_9328157_Turkey Breast.jpg': ['MD 9328157 Turkey Breast'],
        'MK_5392264_Stuffed Churros.jpg': ['MK 5392264 Stuffed Churros'],
        'MK_7391967_Battered Avocado.jpg': ['MK 7391967 Battered Avocado'],
        'RS_5090992_Multi-Color Cauliflower.jpg': ['RS 5090992 Multi-Color Cauliflower'],
        'RS_8463711_Bloody Mary Mix.jpg': ['RS 8463711 Bloody Mary Mix'],
        'RS_9114790_Margarita Mix.jpg': ['RS 9114790 Margarita Mix']
    };

    var _ScoopIssue15Summer2016 = {
        'CL_1752231_Beef Barbacoa.jpg': ['CL 1752231 Beef Barbacoa'],
        'CL_6154634_Turkey Roast.jpg': ['CL 6154634 Turkey Roast'],
        'CL_6385494_Guacamole.jpg': ['CL 6385494 Guacamole'],
        'CL_7250804_White Bread.jpg': ['CL 7250804 White Bread'],
        'CL_8241634_Multigrain Bread.jpg': ['CL 8241634 Multigrain Bread'],
        'CL_9620565_Alfredo Sauce.jpg': ['CL 9620565  Alfredo Sauce'],
        'CVF_5100394_Spring Mix.jpg': ['CVF 5100394 Spring Mix'],
        'DEV_7563995_Choc Mosaic Cake.jpg': ['DEV 7563995 Choc Mosaic Cake'],
        'HB_1376661_Battered Shrimp.jpg': ['HB 1376661 Battered Shrimp'],
        'HB_3699448_Barramundi.jpg': ['HB 3699448 Barramundi'],
        'HB_9641620-7866145_Argentine Shrimp.jpg': ['HB 9641620-7866145 Argentine Shrimp'],
        'HB_A2807458-9791229-8873029_Battered Cod.jpg': ['HB A207458 9791229 8873029 Battered Cod'],
        'MD_2870586-5332373_Roast Beef.jpg': ['HB 2870586-5332373 Roast Beef'],
        'MD_7341372_Maplewood Smoked Ham.jpg': ['MD 7341372 Maplewood Smoked Ham'],
        'MON_2598469_Skipjack Tuna.jpg': ['MON 2598469 Skipjack Tuna'],
        'RS_2211826_Pyramid Tea Variety Pack.jpg': ['RS 2211826 Pyramid Tea Variety Pack'],
        'RS_7637705-8725848_Rice Bran Oil.jpg': ['RS 7637705 8725848 Rice Bran Oil'],
        'RS_8759078_Canola Oil.jpg': ['RS 8759078 Canola Oil'],
        'RS_8892172_Sunflower Oil.jpg': ['RS 8892172 Sunflower Oil']
    };

    var _ScoopIssue2Spring20122 = {
        'CL_ShortRibChuckPatty_GLM1.jpg': ['CL Short Rib Chuck Patty'],
        'CL_ShortRibs.jpg': ['CL Short Ribs'],
        'PF_BreadChickenFritters_APP5.jpg': ['PF Breaded Chicken Fritters A'],
        'PF_BreadChickenFritters_SSC.jpg': ['PF Breaded Chicken Fritters B']
    };

    var _ScoopIssue3Summer20122 = {
        'CL_StuffedPasta_SCC.jpg': ['CL Stuffed Pasta'],
        'CL_StuffedPastaMushTruffCappellucci_LBL1.jpg': ['CL Stuffed Pasta Mushroom Truffle'],
        'CL_StuffedPastaPumpkin_LBL1.jpg': ['CL Stuffed Pasta Pumpkin'],
        'CL_StuffedPastaRoastTomatMozzGirasoli_LBL1.jpg': ['CL Stuffed Pasta Roast Tomato Mozz Girasoli'],
        'HB_CalamariFries.jpg': ['HB Calamari Fries'],
        'HB_CalamariFries_APP1.jpg': ['HB Calamari Fries Plated'],
        'HB_CalamariRings.jpg': ['HB Calamari Rings A'],
        'HB_CalamariRings_APP1.jpg': ['HB Calamari Rings B'],
        'HB_CalamariRings_SSC.jpg': ['HB Calamari Rings C']
    };

    var _ScoopIssue4Fall20122 = {
        'CL_FullyCookedPorkBelly_LBL1.jpg': ['CL Fully Cooked Pork Belly'],
        'MK_Empanada_1.jpg': ['MK Empanada 1'],
        'MK_Empanada_2.jpg': ['MK Empanada 2'],
        'MK_Empanada_3.jpg': ['MK Empanada 3'],
        'PF_FriedChicken_SSC.jpg': ['PF Fried Chicken']
    };

    var _ScoopIssue5Spring20132 = {
        'Chicken_Tenders_A.jpg': ['Chicken Tenders'],
        'CL_AppleCinnGourmetMuffin_GLM1.jpg': ['CL Apple Cinnamon Gourmet Muffins A'],
        'CL_AppleCinnGourmetMuffin_LBL.jpg': ['CL Apple Cinnamon Gourmet Muffins B'],
        'CL_AppleTart_LBL.jpg': ['CL Apple Tart'],
        'CL_BlueberryGourmetMuffins_GLM1.jpg': ['CL Blueberry Gourmet Muffin'],
        'CL_BlueberryMuffin_B.jpg': ['CL Blueberry Muffin'],
        'CL_ChocolateIceCream_LBL.jpg': ['CL Chocolate Ice Cream'],
        'CL_ChocolateIceCream_SSC.jpg': ['CL Vanilla Ice Cream'],
        'CL_DoubleChocGourmetMuffin_GLM1.jpg': ['CL Double Chocolate Gourmet Muffin'],
        'CL_DoubleChocGourmetMuffin_LBL.jpg': ['CL Double Chocolate Gourmet Muffin Plate'],
        'CL_HighGlossBuns_LBL-2.jpg': ['CL High Gloss Buns'],
        'CL_Ice_cream_Appletart_A.jpg': ['CL Ice Cream and Apple Tart'],
        'CL_Muffins_A.jpg': ['CL Muffins A'],
        'CL_Muffins_B.jpg': ['CL Muffins B'],
        'CL_RusticAppleTart_SSC.jpg': ['CL Rustic Apple Tart'],
        'CL_SandwichBunss_SSC.jpg': ['CL Sandwich Buns'],
        'CL_SeededSaletPepperSandwichBuns_LBL.jpg': ['CL Seeded Salt&Pepper Sandwich Buns'],
        'CL_ShrimpCrabCake_A.jpg': ['CL Shrimp Crabcake A'],
        'CL_SouthernStyleShrimpCrabCakes_LBL.jpg': ['CL Southern Style Shrimp Crab Cakes'],
        'CL_TraditionalSandwichBuns_LBL.jpg': ['CL Traditional Sandwich Buns'],
        'CL_VanillaBean_IceCrm_AppleTart.jpg': ['CL Vanilla Bean Ice Cream Apple Tart'],
        'Fries_A.jpg': ['Fries A'],
        'Fries_C.jpg': ['Fries B'],
        'GF_HorseradshChiveCheddarCheeseSlices_GLM1.jpg': ['GF Horseradish Chive Cheddar Cheese Slices'],
        'MD_ChickenBreast.jpg': ['MD Chicken Breast'],
        'MD_OvenRoastedChickenBreast_GLM1.jpg': ['MD Oven Roasted Chicken Breast'],
        'MK_CheeseBites_1.jpg': ['MK Cheese Bites'],
        'MK_MozzarellaEmpanada.jpg': ['MK Mozzarella Empanada'],
        'MK_SnackinBuns_BBQ.jpg': ['MK Snackin Buns BBQ'],
        'MK_SnackinBuns_PhillyCheese.jpg': ['MK Snackin Buns Philly Cheese'],
        'MK_SnackinBuns_SSC.jpg': ['MK Snackin Buns'],
        'MON_BostonMolassesBakedBeans_A.jpg': ['MON Boston Molasses Baked Beans A'],
        'MON_BostonMolassesBakedBeans_C.jpg': ['MON Boston Molasses Baked Beans B'],
        'MON_BourbonMolassesBakedBeans_SSC.jpg': ['MON Bourbon Molasses Baked Beans'],
        'MON_SweetPancakes_2.jpg': ['MON Sweet Pancakes'],
        'MON_SweetPankcakeMix_LBL.jpg': ['MON Sweet Pancake Mix'],
        'PF_BourbonBacon_A.jpg': ['PF Bourbon Bacon']
    };

    var _ScoopIssue6Summer20132 = {
        'Capresse_BG_A.jpg': ['Capresse'],
        'MD-Cover_V2_D_r2.jpg': ['MD Cover'],
        'MD-Cuban_Sandwich_BG_A.jpg': ['MD Cuban Sandwich'],
        'MD_GourmetHam.jpg': ['MD Gourmet Ham'],
        'MD-hot_dogs.jpg': ['MD Hot Dogs'],
        'MD-Roast_Beef_Baguette_BG.jpg': ['MD Roast Beef Baguette']
    };

    var _ScoopIssue7Fall20132 = {
        'CL-BerryTart_C_Scoop.jpg': ['CL BerryTart One'],
        'CL-BerryTart_Web.jpg': ['CL BerryTart Two'],
        'CL-HummusFalafal_A_Scoop.jpg': ['CL Hummus Falafal'],
        'CL-RibeyeRoast_Scoop.jpg': ['CL Ribeye Roast'],
        'CL-Staybowlizer_B.jpg': ['CL Staybowlizer'],
        'CVF-BrusselSprout_B_Scoop.jpg': ['CVF Brussel Sprout'],
        'CVF-Sprouts_A_Scoop.jpg': ['CVF Sprouts'],
        'DP-CotijaCheese_Scoop.jpg': ['DP Cotija Cheese'],
        'DP-FonditoCheese_Scoop.jpg': ['DP Fondito Cheese'],
        'MD-HoneyHam_F_Scoop.jpg': ['MD Honey Ham'],
        'MK-ChipotleBursts_D_Scoop.jpg': ['MK Chipotle Bursts'],
        'MON-Falafel_Web.jpg': ['MON Falafel'],
        'MON-FalafelHummus_A_Scoop.jpg': ['MON Falafel lHummus'],
        'MON-SweetPotatoFries_C_Scoop.jpg': ['MON Sweet Potato Fries'],
        'PF-ChickenFilet_B_Scoop.jpg': ['PF Chicken Filet'],
        'PF-ChickenTender_A_Scoop.jpg': ['PF Chicken Tender'],
        'RS_KeyLimeJuice_2.jpg': ['RS Key Lime Juice'],
        'BoldBeautifulSprouts.jpg': ['BoldBeautifulSprouts'],
        'GetWrappedUp.jpg': ['GetWrappedUp'],
        'HamItUp.jpg': ['HamItUp'],
        'PersonalPizza.jpg': ['PersonalPizza'],
        'ThreeCheersForBeer.jpg': ['ThreeCheersForBeer'],
        'WhatASweetTart.jpg': ['WhatASweetTart'],
        'YouWillFallForFalafel.jpg': ['YouWillFallForFalafel']
    };

    var _ScoopIssue8Spring20142 = {
        'CL SaltedCarmelIceCream1.jpg': ['CL Salted Carmel Ice Cream 1'],
        'CL SaltedCarmelIceCream2.jpg': ['CL Salted Carmel Ice Cream 2'],
        'CL TurkeyBurger1.jpg': ['CL Turkey Burger 1'],
        'CL TurkeyBurger2.jpg': ['CL Turkey Burger 2'],
        'CL TurkeyBurger3.jpg': ['CL Turkey Burger 3'],
        'CVF KaleSaladMix.jpg': ['CVF Kale Salad Mix'],
        'CVF NapaCabbageBlend1.jpg': ['CVF Napa Cabbage Blend 1'],
        'CVF NapaCabbageBlend2.jpg': ['CVF Napa Cabbage Blend 2'],
        'D BlackCherryCheesecake.jpg': ['D Black Cherry Cheesecake'],
        'D Cheesecakes.jpg': ['D Cheesecakes'],
        'D RicottaCheesecake2.jpg': ['D Ricotta Cheesecake 2'],
        'D RicottaCheesecakes.jpg': ['D Ricotta Cheesecakes'],
        'DP StreetTacos.jpg': ['DP Street Tacos'],
        'GF GhostPepperCheese.jpg': ['GF Ghost Pepper Cheese'],
        'HB FreshCrumbCod.jpg': ['HB Fresh Crumb Cod'],
        'HB IslandStyleMahiMahi.jpg': ['HB Island Style Mahi Mahi'],
        'M SweetPotatoWaffleFries.jpg': ['M Sweet Potato Waffle Fries'],
        'M WaffleFries.jpg': ['M Waffle Fries'],
        'MK BeerPretzelCheeseBite1.jpg': ['MK Beer Pretzel Cheese Bite 1'],
        'MK BeerPretzelCheeseBite2.jpg': ['MK Beer Pretzel Cheese Bite 2'],
        'MK BeerPretzelCheeseBite3.jpg': ['MK Beer Pretzel Cheese Bite 3'],
        'MK BeerPretzelCheeseBite4.jpg': ['MK Beer Pretzel Cheese Bite 4'],
        'PF BuffaloChickenChunks.jpg': ['PF Buffalo Chicken Chunks'],
        'PF BuffaloChickenFilet1.jpg': ['PF Buffalo Chicken Filet 1'],
        'PF BuffaloChickenFilet2.jpg': ['PF Buffalo Chicken Filet 2'],
        'PF BuffaloChickenTenders.jpg': ['PF Buffalo Chicken Tenders'],
        'RS Lemonades.jpg': ['RS Lemonades']
    };

    var _ScoopIssue9Summer20142 = {
        'BeefBrisket 5.3x3.58.jpg': ['Beef Brisket'],
        'BeefRibBites 5.3x3.58.jpg': ['Beef Rib Bites'],
        'BlackBeanVeggieBurger 5.3x3.58.jpg': ['Black Bean Veggie Burger'],
        'BuffaloRicottaSpinachRapiniTondi 5.3x3.58.jpg': ['Buffalo Ricotta Spinach Rapini Tondi'],
        'CakePops 5.3x3.58.jpg': ['Cake Pops'],
        'Cakies 5.3x3.58.jpg': ['Cakies'],
        'ChickenChunks 5.3x3.58.jpg': ['Chicken Chunks'],
        'ChickenFilet 5.3x3.58.jpg': ['Chicken Filet'],
        'ChickenTenders 5.3x3.58.jpg': ['Chicken Tenders 2'],
        'CodFries 5.3x3.58.jpg': ['Cod Fries'],
        'CookiesMilk_Cakies 5.3x3.58.jpg': ['Cookies Milk Cakies'],
        'CranberryLemonMuffin 5.3x3.58.jpg': ['Cranberry Lemon Muffin'],
        'EggWhiteMix 5.3x3.58.jpg': ['Egg White Mix'],
        'FishBites 5.3x3.58.jpg': ['Fish Bites'],
        'FreshTomatoSalsa 5.3x3.58.jpg': ['Fresh Tomato Salsa'],
        'GhostPepperMangoSalsa 5.3x3.58.jpg': ['Ghost Pepper Mango Salsa'],
        'GingerTeaMuffin 5.3x3.58.jpg': ['Ginger Tea Muffin'],
        'HeirloomtomatoBurrataMezzalune 5.3x3.58.jpg': ['Heirloom Tomato Burrata Mezzalune'],
        'ItalianSausages 5.3x3.58.jpg': ['Italian Sausages'],
        'KaleTrio 5.3x3.58.jpg': ['Kale Trio'],
        '2KaleTrio 5.3x3.58.jpg': ['Kale Trio 2'],
        'MON_SweetPankcakeMix 5.3x3.58.jpg': ['MON Sweet Pankcake Mix'],
        'NTP Black Bean Burger 5.3x3.58.jpg': ['NTP Black Bean Burger'],
        'PuzzlePotatoes 5.3x3.58.jpg': ['Puzzle Potatoes'],
        'Raspberry_Cakies 5.3x3.58.jpg': ['Raspberry Cakies'],
        'Savory Egg Mix 5.3x3.58.jpg': ['Savory Egg Mix']
    };

    var _ScoopIssue10Fall20142 = {
        'CL_Brat_web.jpg': ['CL_Bratwurst'],
        'CL_ChedJalapMeatBall_web.jpg': ['CL Cheddar Jalapeno Meatball'],
        'CL_CraftMexicanStyleCola.jpg': ['CL Craft Mexican Style Cola'],
        'CL_CraftRootBeer.jpg': ['CL Craft Root Beer'],
        'CL_CraftSodas_All3.jpg': ['CL Craft Sodas All 3'],
        'CL_CraftSpicyGingerBeer.jpg': ['CL Craft Spicy Ginger Beer'],
        'CL_ItalMeatBall_web.jpg': ['CL Italian Meatball'],
        'CL_Short_Rib.jpg': ['CL Short Rib'],
        'CVF_HeirloomTomatoes.jpg': ['CVF Heirloom Tomatoes'],
        'CVF_SunsetBlend.jpg': ['CVF Sunset Blend'],
        'DEV_LemonRaspberry.jpg': ['DEV Lemon Raspberry'],
        'DEV_SweetPotatoMapleLayeredCheeseCake.jpg': ['DEV Sweet Potato Maple Layered Cheesecake'],
        'HarborBanks_Calamari_Web.jpg': ['Harbor Banks Calamari'],
        'HB_TossShrmp_Web.jpg': ['HB Tossed Shrmp'],
        'HV_Pepperoni.jpg': ['HV Pepperoni'],
        'MD_Ham_Web.jpg': ['MD Ham'],
        'MD_HnyRstTurkey_Web.jpg': ['MD Honey Roast Turkey'],
        'MD_KettleCookedPotatoChips_All3.jpg': ['MD Kettle Cooked Potato Chips All 3'],
        'MD_KettleCookedPotatoChips_Barbecue.jpg': ['MD Kettle Cooked Potato Chips Barbecue'],
        'MD_KettleCookedPotatoChips_JalapenoCheddar.jpg': ['MD Kettle Cooked Potato Chips Jalapeno Cheddar'],
        'MD_KettleCookedPotatoChips_Original.jpg': ['MD Kettle Cooked Potato Chips Original'],
        'MK_BaconWrappedChicken_Web.jpg': ['MK Bacon Wrapped Chicken'],
        'MK_CowboyChili_Web.jpg': ['MK Cowboy Chili'],
        'MK_GreenChiliSoup_Web.jpg': ['MK Green Chili Soup'],
        'MK_HamCroquette_Web.jpg': ['MK Ham Croquette'],
        'MON_PickleFries_v2.jpg': ['MON Pickle Fries v2'],
        'MON_PumpSpcMix_Scoop_B.jpg': ['MON Pumpkin Spice Mix Scoop B'],
        'MON_White&SweetPotatoFrites.jpg': ['MON White & Sweet Potato Frites'],
        'PJ_SesamePorkMiniPotStickers.jpg': ['PJ Sesame Pork Mini Pot Stickers'],
        'RS_SunflowerOil.jpg': ['RS Sunflower Oil']
    };

    var _ScoopIssue11Spring20152 = {
        'Scoop11_CL_BellyBurger.jpg': ['CL Belly Burger'],
        'Scoop11_CL_CarolinaBBQ.jpg': ['CL Carolina BBQ'],
        'Scoop11_CL_ChocColaMuffinMinis.jpg': ['CL Choc Cola Muffin Minis'],
        'Scoop11_CL_CoffeeIceCream.jpg': ['CL Coffee Ice Cream'],
        'Scoop11_CL_KansasCityBBQ.jpg': ['CL Kansas City BBQ'],
        'Scoop11_CL_NaturalFry.jpg': ['CL Natural Fry'],
        'Scoop11_CL_PorkCountryRibs.jpg': ['CL Pork Country Ribs'],
        'Scoop11_CL_StrawRhubMuffinMinis.jpg': ['CL Straw Rhub Muffin Minis'],
        'Scoop11_CL_TexasBBQ.jpg': ['CL Texas BBQ'],
        'Scoop11_CL_UmamiTurkeyPatty.jpg': ['CL Umami Turkey Patty'],
        'Scoop11_CVF_SuperfoodSlaw.jpg': ['CVF Superfood Slaw'],
        'Scoop11_GF_SmokyGhostCheeseBlend.jpg': ['GF Smoky Ghost Cheese Blend'],
        'Scoop11_HB_AlaskanCod.jpg': ['HB Alaskan Cod'],
        'Scoop11_HH_SweetCornHoagie.jpg': ['HH Sweet Corn Hoagie'],
        'Scoop11_HH_WheatBeerHoagie.jpg': ['HH Wheat Beer Hoagie'],
        'Scoop11_HV_SavoryBurger.jpg': ['HV Savory Burger'],
        'Scoop11_MD_ChickenSalad.jpg': ['MD Chicken Salad'],
        'Scoop11_MD_FireSmokedHam.jpg': ['MD Fire Smoked Ham'],
        'Scoop11_MD_LoadedBakedPotatoSalad.jpg': ['MD Loaded Baked Potato Salad'],
        'Scoop11_MK_GritStix.jpg': ['MK Grit Stix'],
        'Scoop11_MON_BaconAioli.jpg': ['MON Bacon Aioli'],
        'Scoop11_PF_PepperEncrustedBacon.jpg': ['PF Pepper Encrusted Bacon'],
        'Scoop11_PF_PulledPork.jpg': ['PF Pulled Pork']
    };

    var _ScoopIssue12Summer20152 = {
        'Scoop12_CL_MediterraneanStyleSliders.jpg': ['CL Greek Sliders'],
        'Scoop12_CS_RawBeefCuts_Enchiladas.jpg': ['CL Raw Beef Cuts Enchiladas'],
        'Scoop12_CVF_RoosterPotatoes.jpg': ['CVF Rooster Potatoes'],
        'Scoop12_DS_CroissantDonuts.jpg': ['DBS Croissant Donuts'],
        'Scoop12_HB_FlourDustedAlaskanSole.jpg': ['HB Flour Dusted Alaskan Sole'],
        'Scoop12_HB_SpicyTossNServeShrimp.jpg': ['HB Spicy Toss N Serve Shrimp'],
        'Scoop12_HH_PotatoHamburgerBuns.jpg': ['HH Potato Hamburger Buns'],
        'Scoop12_HH_PullApartCinnamonRoll.jpg': ['HH Pull Apart Cinnamon Roll'],
        'Scoop12_MON_CarolinaReaperWingSauce.jpg': ['MON Carolina Reaper Wing Sauce'],
        'Scoop12_MON_SmashedPotatoSkin.jpg': ['MON Smashed Potato Skins'],
        'Scoop12_PF_BeerBatterChixChunks.jpg': ['PF Beer Battered Chix Chunks'],
        'Scoop12_PF_HardwoodChickenWings.jpg': ['PF Hardwood Chicken Wings'],
        'Scoop12_RS_WhiteStoneGroundGrits.jpg': ['RS White Stone Ground Grits'],
        'benedoughnut.jpg': ['Bene Doughnut'],
        'Caprese.jpg': ['Caprese'],
        'Cover.jpg': ['Cover'],
        'FilledGlazed.jpg': ['Filled Glazed'],
        'JuicyLuicy.jpg': ['Juicy Luicy'],
        'LobsterRoll.jpg': ['Lobster Roll'],
        'MonteCristo.jpg': ['Monte Cristo'],
        'MplBourbonBacon.jpg': ['Maple Bourbon Bacon'],
        'SaltySweet.jpg': ['Salty Sweet'],
        'SmkdSalmon.jpg': ['Smoked Salmon'],
        'Smore.jpg': ['Smores'],
        'StrawShortcake.jpg': ['Strawberry Shortcake']
    };

    var _ScoopIssue13Fall20152 = {
        'Bratwurst-5.3x3.5813.jpg': ['CL Bratwurst'],
        'Cinn-Brown-Sugar-Ice-Cream-5.3x3.5824.jpg': ['CL Cinnamon & Brown Sugar Ice Cream'],
        'Grass-Fed-Burger-5.3x3.5822.jpg': ['CL Grass Fed Burger'],
        'Grill Sidebar5.3x3.583.jpg': ['CL Grill Sidebar'],
        'Ground Chorizo-5.3x3.5820.jpg': ['CL Ground Chorizo'],
        'Hot-Italian-Sausage-5.3x3.5811.jpg': ['CL Hot Italian Sausage'],
        'Korean-Barbecue-Sauce5.3x3.587.jpg': ['CL Korean Barbecue Sauce'],
        'Sweet-Italian-Sausage-5.3x3.5812.jpg': ['CL Sweet Italian Sausage'],
        'Diced-Mangoes-5.3x3.584.jpg': ['CVF Fresh Diced Magnoes'],
        'Chipotle-Salsa-Picada-5.3x3.5817.jpg': ['DP Cipotle Salsa Picada'],
        'Cuban-Pork-Roast-5.3x3.5810.jpg': ['MD Cuban Seasoned Pork Roast'],
        'Salt-Vinegar-Chips-5.3x3.588.jpg': ['MD Salt Vinegar Chips'],
        'Sour-CreamChives-Chips-5.3x3.589.jpg': ['MD Sour Cream Chives Chips'],
        'Whiskey-Onion-Rings-5.3x3.5814.jpg': ['MK Whiskey Battered Onion Rings'],
        'Shot-Onion-Rings-5.3x3.5815.jpg': ['MKShot & Beer Battered Onion Rings'],
        'Mirepoix-Blend-5.3x3.5819.jpg': ['MON Mirepoix Blend'],
        'Puzzle-Potatoes-5.3x3.585.jpg': ['MON Puzzle Potatoes'],
        'Sweet-Potato-Waffle-Fries-5.3x3.586.jpg': ['MON Sweet Potato Waffle Fries'],
        'Nashville-Hot-Chicken-Wings-5.3x3.5816.jpg': ['PF Nashville Hot Chicken Wings'],
        'Iced-Latte--5.3x3.58.jpg': ['RIT Iced Latte'],
        'Grilled-Vegetables-5.3x3.5818.jpg': ['RS Grilled Vegetables'],
        'Thermometer-5.3x3.582.jpg': ['SUP Thermometer'],
        'Short-Rib-Slices-5.3x3.5821.jpg': ['SY Short Rib Slices']
    };

    var _ScoopIssue14Spring20162 = {
        'Valencia-Orange-Juice_5.25x3.377.jpg': ['RS 100% Valencia Orange Juice'],
        'All-Natural-Cherrywood-Smokde-Bacon_5.25x3.377.jpg': ['PF All Natural Cherrywood Smoked Bacon'],
        'All-Natural-Chipotle-Chicken-Thighs_5.25x3.377.jpg': ['CL All Natural Chipotle Chicken Thighs'],
        'All-Natural-Dark-turkey-Deli-Meat_5.25x3.377.jpg': ['MD All Natural Dark Turkey Deli Meat'],
        'All-Natural-Grass-Fed-Burger_5.25x3.377.jpg': ['SY All Natural Grass Fed Burger'],
        'All-Natural-Hickory-Smoked-Half-Chicken_5.25x3.377.jpg': ['CL All Natural Hickory Smoked half Chicken'],
        'All-Natural-Pork-Burnt-Ends_5.25x3.377.jpg': ['CL All Natural Pork Burnt Ends'],
        'All-Natural-Pork-Carnitas_5.25x3.377.jpg': ['CL All Natural Pork Carnitas'],
        'Avero-Gold_5.25x3.377.jpg': ['Avero Gold'],
        'Baby-Savoy-Spinach_5.25x3.377.jpg': ['CVF Baby Savoy Spinach Blend'],
        'Bavarian-Soft-Pretzel_5.25x3.377.jpg': ['CL Bavarian Soft Pretzel'],
        'Beer-Cheese-Dip_5.25x3.377.jpg': ['MK Beer Cheese Dip'],
        'Bianco-Buns_5.25x3.377.jpg': ['CL Bianco Buns'],
        'Blood-Orange-Sorbet_5.25x3.377.jpg': ['CL Blood Orange Sorbet'],
        'Bloody-Mary-Mix_5.25x3.377.jpg': ['RS Bloody Mary Mix'],
        'Cold-Brew-Coffee_Concentrate_5.25x3.377.jpg': ['RIT Cold Brew Coffee Concentrate'],
        'Fingerling-Sweet-Potatoes_5.25x3.377.jpg': ['CVF Fingerling Sweet Potatoes'],
        'Peper-and-Smoked-Sugar-Marinated-Alaska-Sockeye-Salmon_5.25x3.377.jpg': ['CL Pepper & Smoked Sugar Marinated Alaskan Sockey Salmon'],
        'Plain-Greek-Nonfat-Yogurt_5.25x3.377.jpg': ['GF Plain Greek Nonfat Yogurt'],
        'Riced-Cauliflower_5.25x3.377.jpg': ['CVF Riced Cauliflower'],
        'Roasted-Garlic-Buns_5.25x3.377.jpg': ['CL Roasted Garlic Buns'],
        'Slow-Roasted-Tomatoes_5.25x3.377.jpg': ['RS Slow Roasted Tomatoes'],
        'Spreadable-Brie_5.25x3.377.jpg': ['GF Spreadable Brie'],
        'Strawberry-Rhubarb-Greek-Nonfat-Yogurt_5.25x3.377.jpg': ['GF Strawberry Rhubarb Greek Nonfat Yogurt'],
        'Vanilla-Greek-Nonfat-Yogurt_5.25x3.377.jpg': ['GF Vanilla Greek Nonfat Yogurt'],
        'Watermelon-Limeade_5.25x3.377.jpg': ['RS Watermelon Limeade'],
        'White-and-Sweet-Potatoes-Frites_5.25x3.377.jpg': ['MON White & Sweet Potatoe Frites']
    };

    var _ScoopIssue16Fall20162 = {
        'CL_2561366_Demi Glace.jpg': ['CL Demi Glace'],
        'CL_3688845_Pumpkin Sweet Potato Tart.jpg': ['CL Pumpkin Sweet Potato Tart'],
        'CL_5816564_Pork Loin.jpg': ['CL Pork Loin'],
        'CL_7095673_Natural Chip.jpg': ['CL Natural Chip'],
        'CL_7265587_Compound Butter.jpg': ['CL Compound Butter'],
        'CL_8808558_Pumpkin Spice Ice Cream.jpg': ['CL Pumpkin Spice Ice Cream'],
        'CL_9192185_Yellowfin Tuna Slices.jpg': ['CL Yellowfin Tuna Slices'],
        'CL_9465510_Beef Chuck Short Ribs.jpg': ['CL Beef Chuck Short Ribs'],
        'CL_9636044_Natural Fry.jpg': ['CL Natural Fry'],
        'CVF_5225864_Beefsteak Tomatoes.jpg': ['CVF Beefsteak Tomatoes'],
        'CVF_8858409_Sunset Blend.jpg': ['CVF Sunset Blend'],
        'DEV_3998334_Smore Lava Cake.jpg': ['DEV Smore Lava Cake'],
        'GF_1056622_Blue Cheese Crumbles.jpg': ['GF Blue Cheese Crumbles'],
        'HB_1714015_Stuffed Shrimp and Grits.jpg': ['HB Stuffed Shrimp and Grits'],
        'HB_3305058_Stuff Shrimp Southwest.jpg': ['HB Stuffed Shrimp Southwest'],
        'HH_4496241_Hawaiian Slider Bun.jpg': ['HH Hawaiian Slider Bun'],
        'HH_4649764_Brown Breadstick.jpg': ['HH Brown Breadstick'],
        'HH_5825665_Garlic Ciabatta Breadstick.jpg': ['HH Garlic Ciabatta Breadstick'],
        'MD_2565976_Applewood Turkey Breast.jpg': ['MD Applewood Turkey Breast'],
        'MON_8869687_Pickle Fries.jpg': ['MON Pickle Fries'],
        'PF_7637713_Tenderloin Fritters.jpg': ['PF Tenderloin Fritters'],
        'RS_3616429_Grilled Artichokes.jpg': ['RS Grilled Artichokes'],
        'RS_9726983_Caramelized Onions.jpg': ['RS Caramelized Onions'],
        'SY_1846585_Bone Marrow.jpg': ['SY Bone Barrow'],
        'SY_7127324_Grass Fed Sliders.jpg': ['SY Grass Fed Sliders'],
        'SY_9518653_Ribeye.jpg': ['SY Ribeye']
    };

    var _ScoopIssue19Fall20172 = {
        'CL_4562638_CornMuffin.jpg': ['CL 4562638 Corn Muffin'],
        'CL_7617327_PorkLoin.jpg': ['CL 7617327 Pork Loin'],
        'CL_8808558_PumpSpiceIceCream.jpg': ['CL 8808558 Pumpkin Spice Ice Cream'],
        'CVF_4882244_1245731_VeggieCrunch.jpg': ['CVF 4882244 1247531 Veggie Crunch'],
        'CVF_9484217_RotiniSalad.jpg': ['CVF 9484217 Rotini Salad'],
        'DEV_6968216_BelgianWaffle.jpg': ['DEV 6968216 Belgian Waffle'],
        'DEV_8848186_Cheesecake.jpg': ['DEV 8848186 Cheesecake'],
        'GVF_5337015_LiquidEggs.jpg': ['GVF 5337015 Liquid Eggs'],
        'HB_3198825_CapeShark.jpg': ['HB 3198825 Cape Shark'],
        'HB_3216914_NorwegianTrout.jpg': ['HB 3216914 Norwegian Trout'],
        'HB_9823791_Norwegian-Salmon.jpg': ['HB 9823791 Norwegian Salmon'],
        'MK_6442845_Cauliflower.jpg': ['MK 6442845 Cauliflower'],
        'MON_7693799_SweetPotatoFry.jpg': ['MON 7693799 Sweet Potato Fry'],
        'PF_5815653_BaconSausage.jpg': ['PF 5815653 Bacon Sausage'],
        'PF_7699403_Chicken-Breast.jpg': ['PF 7699403 Chicken Breast'],
        'PF_8638719_Fried-Chicken-Thigh.jpg': ['PF 8638719 Fried Chicken Thigh'],
        'PF_9986258_ChickenWings.jpg': ['PF 9986258 Chicken Wings'],
        'RS_6537988_GrilledVeggies.jpg': ['RS 6537988 Grilled Veggies']
    };

    var _ScoopIssue18Summer20172 = {
        'CL_1088051_BeefBacon.jpg': ['CL 1088051 Beef Bacon'],
        'CL_1462630_ChickenTenderloin.jpg': ['CL 1462630 Chicken Tenderloin'],
        'CL_4493997_KouignAmann.jpg': ['CL 4493997 Kouign Amann'],
        'CL_9841549_StrawIceCream.jpg': ['CL 9841549 Strawberry Ice Cream'],
        'CVF_6866621_Kohlrabi.jpg': ['CVF 6866621 Kohlrabi'],
        'DEV_7025143_FunnelSticks.jpg': ['DEV 7025143 Funnel Sticks'],
        'DP_5584556_BorrachoBeans.jpg': ['DP 5584556 Borracho Beans'],
        'HB_7497505_StripedBass.jpg': ['HB 7497505 Striped Bass'],
        'HB_8417215_ArcticChar.jpg': ['HB 8417215 Artic Char'],
        'MD_3131044_BlkForestHam.jpg': ['MD 3131044 Black Forest Ham'],
        'MD_3413690_PopcornCheddar.jpg': ['MD 3413690 Popcorn Cheddar'],
        'MD_5620686_Popcorn_CocoOilSalt.jpg': ['MD 5620686 Popcorn Coconut Oil Salt'],
        'MK_3043713_MeatlessWings.jpg': ['MK 3043713 Meatless Wings'],
        'MK_4503294_BeerandCheeseDip.jpg': ['MK 4503294 Beer and Cheese Dip'],
        'MK_5922686_MeatlessCrumbles.jpg': ['MK 5922686 Meatless Crumbles'],
        'MK_5942572_CornNugget.jpg': ['MK 5942572 Corn Nugget'],
        'PF_3440787_JowlBacon.jpg': ['PF 3440787 Jowl Bacon'],
        'PF_8371487_Chick-arrones.jpg': ['PF 8371487 Chick-Arrones'],
        'SY_1345296_RWAChuck.jpg': ['SY 1345296 RWA Chuck']
    };

    var _ScoopIssue17Spring20172 = {
        'CL_1123735_Brisket.jpg': ['CL 1123735 Brisket'],
        'CL_1185055_Beef&Truffle Patties.jpg': ['CL 1185055 Beef & Truffle Patties'],
        'CL_2364959_Turkey Burger.jpg': ['CL 2364959 Turkey Burger'],
        'CL_2441422_Torta Buns.jpg': ['CL 2441422 Torta Buns'],
        'CL_2663960_Grilled Chicken Breast.jpg': ['CL 2663960 Grilled Chicken Breast'],
        'CL_3552695_Chicken Shawarma.jpg': ['CL 3552695 Chicken Shawarma'],
        'CL_4264835_Cheddar&Onion Bialys.jpg': ['CL 4264835 Cheddar & Onion Bialys'],
        'CL_8601429_Mini Naan.jpg': ['CL 8601429 Mini Naan'],
        'CL_9192185_Yellowfin Tuna Slices.jpg': ['CL 9192185 Yellowfin Tuna Slices'],
        'CVF_3116609_Lemony Rocket Blend.jpg': ['CVF 3116609 Lemony Rocket Blend'],
        'DEV_1195093_Black Velvet Cookie.jpg': ['DEV 1195093 Black Velvet Cookie'],
        'DEV_8848129_Lem-Ras Cheesecake.jpg': ['DEV 8848129 Lem-Ras Cheesecake'],
        'HB_9936302_Corkskrew Shrimp.jpg': ['HB 9936302 Corkskrew Shrimp'],
        'MD_9328157_Turkey Breast.jpg': ['MD 9328157 Turkey Breast'],
        'MK_5392264_Stuffed Churros.jpg': ['MK 5392264 Stuffed Churros'],
        'MK_7391967_Battered Avocado.jpg': ['MK 7391967 Battered Avocado'],
        'RS_5090992_Multi-Color Cauliflower.jpg': ['RS 5090992 Multi-Color Cauliflower'],
        'RS_8463711_Bloody Mary Mix.jpg': ['RS 8463711 Bloody Mary Mix'],
        'RS_9114790_Margarita Mix.jpg': ['RS 9114790 Margarita Mix']
    };

    var _ScoopIssue15Summer20162 = {
        'CL_1752231_Beef Barbacoa.jpg': ['CL 1752231 Beef Barbacoa'],
        'CL_6154634_Turkey Roast.jpg': ['CL 6154634 Turkey Roast'],
        'CL_6385494_Guacamole.jpg': ['CL 6385494 Guacamole'],
        'CL_7250804_White Bread.jpg': ['CL 7250804 White Bread'],
        'CL_8241634_Multigrain Bread.jpg': ['CL 8241634 Multigrain Bread'],
        'CL_9620565_Alfredo Sauce.jpg': ['CL 9620565  Alfredo Sauce'],
        'CVF_5100394_Spring Mix.jpg': ['CVF 5100394 Spring Mix'],
        'DEV_7563995_Choc Mosaic Cake.jpg': ['DEV 7563995 Choc Mosaic Cake'],
        'HB_1376661_Battered Shrimp.jpg': ['HB 1376661 Battered Shrimp'],
        'HB_3699448_Barramundi.jpg': ['HB 3699448 Barramundi'],
        'HB_9641620-7866145_Argentine Shrimp.jpg': ['HB 9641620-7866145 Argentine Shrimp'],
        'HB_A2807458-9791229-8873029_Battered Cod.jpg': ['HB A207458 9791229 8873029 Battered Cod'],
        'MD_2870586-5332373_Roast Beef.jpg': ['HB 2870586-5332373 Roast Beef'],
        'MD_7341372_Maplewood Smoked Ham.jpg': ['MD 7341372 Maplewood Smoked Ham'],
        'MON_2598469_Skipjack Tuna.jpg': ['MON 2598469 Skipjack Tuna'],
        'RS_2211826_Pyramid Tea Variety Pack.jpg': ['RS 2211826 Pyramid Tea Variety Pack'],
        'RS_7637705-8725848_Rice Bran Oil.jpg': ['RS 7637705 8725848 Rice Bran Oil'],
        'RS_8759078_Canola Oil.jpg': ['RS 8759078 Canola Oil'],
        'RS_8892172_Sunflower Oil.jpg': ['RS 8892172 Sunflower Oil']
    };

    var _path = "http://www.four51.com/Themes/Custom/78ad1fd0-1ab1-4bd2-9a1a-a556f7bc77dc/ImageSelectorImages/TableTents/"

    return {
        ScoopIssue2Spring2012 : _ScoopIssue2Spring2012,
        ScoopIssue3Summer2012 : _ScoopIssue3Summer2012,
        ScoopIssue4Fall2012 : _ScoopIssue4Fall2012,
        ScoopIssue5Spring2013 : _ScoopIssue5Spring2013,
        ScoopIssue6Summer2013 : _ScoopIssue6Summer2013,
        ScoopIssue7Fall2013 : _ScoopIssue7Fall2013,
        ScoopIssue8Spring2014 : _ScoopIssue8Spring2014,
        ScoopIssue9Summer2014 : _ScoopIssue9Summer2014,
        ScoopIssue10Fall2014 : _ScoopIssue10Fall2014,
        ScoopIssue11Spring2015 : _ScoopIssue11Spring2015,
        ScoopIssue12Summer2015 : _ScoopIssue12Summer2015,
        ScoopIssue13Fall2015 : _ScoopIssue13Fall2015,
        ScoopIssue14Spring2016 : _ScoopIssue14Spring2016,
        ScoopIssue16Fall2016 : _ScoopIssue16Fall2016,
        ScoopIssue19Fall2017 : _ScoopIssue19Fall2017,
        ScoopIssue18Summer2017 : _ScoopIssue18Summer2017,
        ScoopIssue17Spring2017 : _ScoopIssue17Spring2017,
        ScoopIssue15Summer2016 : _ScoopIssue15Summer2016,
        ScoopIssue2Spring20122 : _ScoopIssue2Spring20122,
        ScoopIssue3Summer20122 : _ScoopIssue3Summer20122,
        ScoopIssue4Fall20122 : _ScoopIssue4Fall20122,
        ScoopIssue5Spring20132 : _ScoopIssue5Spring20132,
        ScoopIssue6Summer20132 : _ScoopIssue6Summer20132,
        ScoopIssue7Fall20132 : _ScoopIssue7Fall20132,
        ScoopIssue8Spring20142 : _ScoopIssue8Spring20142,
        ScoopIssue9Summer20142 : _ScoopIssue9Summer20142,
        ScoopIssue10Fall20142 : _ScoopIssue10Fall20142,
        ScoopIssue11Spring20152 : _ScoopIssue11Spring20152,
        ScoopIssue12Summer20152 : _ScoopIssue12Summer20152,
        ScoopIssue13Fall20152 : _ScoopIssue13Fall20152,
        ScoopIssue14Spring20162 : _ScoopIssue14Spring20162,
        ScoopIssue16Fall20162 : _ScoopIssue16Fall20162,
        ScoopIssue19Fall20172 : _ScoopIssue19Fall20172,
        ScoopIssue18Summer20172 : _ScoopIssue18Summer20172,
        ScoopIssue17Spring20172 : _ScoopIssue17Spring20172,
        ScoopIssue15Summer20162 : _ScoopIssue15Summer20162,
        path : _path
    }
});